mod common;
mod compress;
mod convert_image;
mod encrypt;
mod images_to_pdf;
mod merge;
mod reorder;
mod split;
mod uninstall;
mod update;
mod watermark;

pub(crate) use compress::handle_compress;
pub(crate) use convert_image::handle_convert_image;
pub(crate) use encrypt::handle_encrypt;
pub(crate) use images_to_pdf::handle_images_to_pdf;
pub(crate) use merge::handle_merge;
pub(crate) use reorder::handle_reorder;
pub(crate) use split::handle_split;
pub(crate) use uninstall::handle_uninstall;
pub(crate) use update::handle_update;
pub(crate) use watermark::handle_watermark;
